apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: {{.Release.Name}}-drupal-node-service
  namespace: {{.Release.Namespace}}
spec:
  # clusterIP: 10.102.188.158
  # clusterIPs:
  # - 10.102.188.158
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{.Values.nodePortService.nodePort}}
    port: {{.Values.nodePortService.port}}
    protocol: TCP
    targetPort: {{.Values.nodePortService.port}}
  selector:
    app: drupal
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
