apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: drupal-node-service
  namespace: default
spec:
  clusterIP: 10.43.0.0.1
  clusterIPs:
  - 10.43.0.0.1
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: drupal
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
